name: Preconfigured Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Configure and build project
      run: |
        cmake . && make

    - name: Run tests and generate coverage
      run: |
        ctest --verbose
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # Remove system header files from coverage
        genhtml coverage.info --output-directory ./coverage/ # Generate HTML report

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./coverage/
  check-complexity:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/checkout@v2

    - name: Install Lizard
      run: sudo apt-get install python3-pip && pip3 install lizard

    - name: Check Code Complexity
      run: lizard -C 3
